[package]
name = "routing"
version = "0.1.0"
authors = ["yguan <yguan@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
plotters = "^0.3.0"
statrs = "*"